# Generated by Django 4.2.11 on 2024-05-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0003_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contact_info',
            field=models.CharField(default='', max_length=255),
        ),
    ]
