# Generated by Django 4.2.11 on 2024-05-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0004_alter_customuser_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
