# Generated by Django 4.2.11 on 2024-05-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0007_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Заказчик'), ('performer', 'Исполнитель')], default='customer', max_length=20),
        ),
    ]
